version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: mysql_portal
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bismillah
      MYSQL_DATABASE: portal
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    volumes:
      - ./data/portal:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 7000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: bismillah
      MYSQL_ROOT_PASSWORD: root
